version: '2.2'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user 
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      # RabbitMQ instance
      - '5672:5672'
      # Web interface
      - '15672:15672'